export enum VideogameGenres {
  Adventure = 'Adventure',
  Arcade = 'Arcade',
  CardAndBoardGame = 'Card & Board Game',
  Fighting = 'Fighting',
  HackAndSlashBeatEmUp = 'Hack and slash/Beat \'em up',
  Indie = 'Indie',
  MOBA = 'MOBA',
  Music = 'Music',
  Platform = 'Platform',
  PointAndClick = 'Point-and-click',
  Puzzle = 'Puzzle',
  Racing = 'Racing',
  RPG = 'Role-playing (RPG)',
  RTS = 'Real Time Strategy (RTS)',
  Simulator = 'Simulator',
  Shooter = 'Shooter',
  Sport = 'Sport',
  Strategy = 'Strategy',
  Tactical = 'Tactical',
  TBS = 'Turn-based strategy (TBS)',
  QuizTrivia = 'Quiz/Trivia',
  VisualNovel = 'Visual Novel'
  }
